spring.mvc.apiversion.use.header=Api-Version
#spring.datasource.url=jdbc:h2:mem:job-portal-db
spring.datasource.url=jdbc:h2:file:C:/Users/karthik.sridhara/Documents/LearningImp/SpringBoot_EasyByte/section05/jobportal-db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
#spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
spring.sql.init.data-locations=classpath:sql/jobportal-data.sql
logging.level.org.springframework.jdbc.datasource.init=DEBUG
